WITH scoped_relations AS (
 SELECT c.*,n.nspname FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace
 WHERE n.nspname IN ('public','logs','security_internal') AND c.relkind IN ('r','p','v','m','S','f')
), scoped_functions AS (
 SELECT p.*,n.nspname FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace
 WHERE n.nspname IN ('public','logs','security_internal') AND p.prokind IN ('f','p')
)
SELECT jsonb_build_object(
 'capturedAt',clock_timestamp(), 'databaseVersion',version(), 'evidenceKind','metadata-only scoped schema reconstruction snapshot; NOT pg_dump or backup',
 'schemas',(SELECT coalesce(jsonb_agg(jsonb_build_object('name',nspname,'owner',pg_get_userbyid(nspowner),'acl',nspacl::text) ORDER BY nspname),'[]') FROM pg_namespace WHERE nspname IN ('public','logs','security_internal')),
 'roles',(SELECT coalesce(jsonb_agg(jsonb_build_object('name',rolname,'login',rolcanlogin,'superuser',rolsuper,'bypassRls',rolbypassrls,'inherit',rolinherit,'createRole',rolcreaterole,'createDatabase',rolcreatedb,'replication',rolreplication) ORDER BY rolname),'[]') FROM pg_roles WHERE rolname IN ('postgres','anon','authenticated','service_role','supabase_admin','supabase_auth_admin','supabase_storage_admin')),
 'roleMemberships',(SELECT coalesce(jsonb_agg(jsonb_build_object('role',pg_get_userbyid(roleid),'member',pg_get_userbyid(member),'grantor',pg_get_userbyid(grantor),'adminOption',admin_option,'inheritOption',inherit_option,'setOption',set_option) ORDER BY roleid,member),'[]') FROM pg_auth_members WHERE roleid IN (SELECT oid FROM pg_roles WHERE rolname IN ('postgres','anon','authenticated','service_role','supabase_admin','supabase_auth_admin','supabase_storage_admin')) OR member IN (SELECT oid FROM pg_roles WHERE rolname IN ('postgres','anon','authenticated','service_role','supabase_admin','supabase_auth_admin','supabase_storage_admin'))),
 'defaultPrivileges',(SELECT coalesce(jsonb_agg(jsonb_build_object('owner',pg_get_userbyid(d.defaclrole),'schema',n.nspname,'objectType',d.defaclobjtype,'acl',d.defaclacl::text) ORDER BY d.defaclrole,d.defaclnamespace,d.defaclobjtype),'[]') FROM pg_default_acl d LEFT JOIN pg_namespace n ON n.oid=d.defaclnamespace WHERE n.nspname IN ('public','logs','security_internal') OR d.defaclnamespace=0),
 'relations',(SELECT coalesce(jsonb_agg(jsonb_build_object('schema',c.nspname,'name',c.relname,'kind',c.relkind,'owner',pg_get_userbyid(c.relowner),'acl',c.relacl::text,'rls',c.relrowsecurity,'forceRls',c.relforcerowsecurity,'options',c.reloptions,'persistence',c.relpersistence,'replicaIdentity',c.relreplident,'viewDefinition',CASE WHEN c.relkind IN ('v','m') THEN pg_get_viewdef(c.oid,true) END,'partitionKey',CASE WHEN c.relkind='p' THEN pg_get_partkeydef(c.oid) END,'partitionBound',CASE WHEN c.relispartition THEN pg_get_expr(c.relpartbound,c.oid) END) ORDER BY c.nspname,c.relname),'[]') FROM scoped_relations c),
 'columns',(SELECT coalesce(jsonb_agg(jsonb_build_object('schema',c.nspname,'table',c.relname,'name',a.attname,'position',a.attnum,'type',format_type(a.atttypid,a.atttypmod),'typeSchema',tn.nspname,'typeName',t.typname,'notNull',a.attnotnull,'default',pg_get_expr(ad.adbin,ad.adrelid),'identity',a.attidentity,'generated',a.attgenerated,'collation',CASE WHEN a.attcollation<>0 THEN a.attcollation::regcollation::text END,'acl',a.attacl::text,'storage',a.attstorage,'compression',a.attcompression) ORDER BY c.nspname,c.relname,a.attnum),'[]') FROM scoped_relations c JOIN pg_attribute a ON a.attrelid=c.oid JOIN pg_type t ON t.oid=a.atttypid JOIN pg_namespace tn ON tn.oid=t.typnamespace LEFT JOIN pg_attrdef ad ON ad.adrelid=c.oid AND ad.adnum=a.attnum WHERE c.relkind<>'S' AND a.attnum>0 AND NOT a.attisdropped),
 'constraints',(SELECT coalesce(jsonb_agg(jsonb_build_object('schema',n.nspname,'table',c.relname,'name',k.conname,'type',k.contype,'definition',pg_get_constraintdef(k.oid,true),'validated',k.convalidated,'deferrable',k.condeferrable,'initiallyDeferred',k.condeferred,'inherited',k.conislocal,'noInherit',k.connoinherit) ORDER BY n.nspname,c.relname,k.conname),'[]') FROM pg_constraint k JOIN pg_namespace n ON n.oid=k.connamespace LEFT JOIN pg_class c ON c.oid=k.conrelid WHERE n.nspname IN ('public','logs','security_internal')),
 'indexes',(SELECT coalesce(jsonb_agg(jsonb_build_object('schema',c.nspname,'table',c.relname,'name',ic.relname,'owner',pg_get_userbyid(ic.relowner),'definition',pg_get_indexdef(i.indexrelid),'primary',i.indisprimary,'unique',i.indisunique,'valid',i.indisvalid,'ready',i.indisready,'constraintOwned',EXISTS(SELECT 1 FROM pg_constraint k WHERE k.conindid=i.indexrelid),'options',ic.reloptions) ORDER BY c.nspname,c.relname,ic.relname),'[]') FROM scoped_relations c JOIN pg_index i ON i.indrelid=c.oid JOIN pg_class ic ON ic.oid=i.indexrelid),
 'sequences',(SELECT coalesce(jsonb_agg(jsonb_build_object('schema',c.nspname,'name',c.relname,'owner',pg_get_userbyid(c.relowner),'acl',c.relacl::text,'type',format_type(s.seqtypid,NULL),'start',s.seqstart::text,'increment',s.seqincrement::text,'min',s.seqmin::text,'max',s.seqmax::text,'cache',s.seqcache::text,'cycle',s.seqcycle,'ownedBy',(SELECT jsonb_build_object('schema',tn.nspname,'table',tc.relname,'column',a.attname,'dependencyType',d.deptype) FROM pg_depend d JOIN pg_class tc ON tc.oid=d.refobjid JOIN pg_namespace tn ON tn.oid=tc.relnamespace JOIN pg_attribute a ON a.attrelid=tc.oid AND a.attnum=d.refobjsubid WHERE d.classid='pg_class'::regclass AND d.objid=c.oid AND d.refclassid='pg_class'::regclass AND d.deptype IN ('a','i') LIMIT 1)) ORDER BY c.nspname,c.relname),'[]') FROM scoped_relations c JOIN pg_sequence s ON s.seqrelid=c.oid),
 'functions',(SELECT coalesce(jsonb_agg(jsonb_build_object('schema',p.nspname,'name',p.proname,'identityArgs',pg_get_function_identity_arguments(p.oid),'definition',pg_get_functiondef(p.oid),'owner',pg_get_userbyid(p.proowner),'acl',p.proacl::text,'definer',p.prosecdef,'config',p.proconfig,'volatility',p.provolatile,'parallel',p.proparallel) ORDER BY p.nspname,p.proname,pg_get_function_identity_arguments(p.oid)),'[]') FROM scoped_functions p),
 'triggers',(SELECT coalesce(jsonb_agg(jsonb_build_object('schema',n.nspname,'table',c.relname,'name',t.tgname,'definition',pg_get_triggerdef(t.oid,true),'enabled',t.tgenabled) ORDER BY n.nspname,c.relname,t.tgname),'[]') FROM pg_trigger t JOIN pg_class c ON c.oid=t.tgrelid JOIN pg_namespace n ON n.oid=c.relnamespace JOIN pg_proc p ON p.oid=t.tgfoid JOIN pg_namespace fn ON fn.oid=p.pronamespace WHERE NOT t.tgisinternal AND (n.nspname IN ('public','logs','security_internal') OR (n.nspname='auth' AND fn.nspname IN ('public','logs','security_internal')))),
 'policies',(SELECT coalesce(jsonb_agg(to_jsonb(p) ORDER BY schemaname,tablename,policyname),'[]') FROM pg_policies p WHERE schemaname IN ('public','logs','security_internal','storage')),
 'types',(SELECT coalesce(jsonb_agg(jsonb_build_object('schema',n.nspname,'name',t.typname,'kind',t.typtype,'owner',pg_get_userbyid(t.typowner),'acl',t.typacl::text,'baseType',CASE WHEN t.typbasetype<>0 THEN format_type(t.typbasetype,t.typtypmod) END,'notNull',t.typnotnull,'default',t.typdefault,'enumLabels',(SELECT jsonb_agg(e.enumlabel ORDER BY e.enumsortorder) FROM pg_enum e WHERE e.enumtypid=t.oid)) ORDER BY n.nspname,t.typname),'[]') FROM pg_type t JOIN pg_namespace n ON n.oid=t.typnamespace WHERE n.nspname IN ('public','logs','security_internal') AND t.typtype IN ('e','d')),
 'extensions',(SELECT coalesce(jsonb_agg(jsonb_build_object('name',e.extname,'version',e.extversion,'schema',n.nspname,'owner',pg_get_userbyid(e.extowner),'relocatable',e.extrelocatable) ORDER BY e.extname),'[]') FROM pg_extension e JOIN pg_namespace n ON n.oid=e.extnamespace),
 'buckets',(SELECT coalesce(jsonb_agg(jsonb_build_object('id',id,'name',name,'public',public,'fileSizeLimit',file_size_limit::text,'allowedMimeTypes',allowed_mime_types) ORDER BY id),'[]') FROM storage.buckets),
 'publications',(SELECT coalesce(jsonb_agg(jsonb_build_object('name',p.pubname,'owner',pg_get_userbyid(p.pubowner),'allTables',p.puballtables,'insert',p.pubinsert,'update',p.pubupdate,'delete',p.pubdelete,'truncate',p.pubtruncate,'viaPartitionRoot',p.pubviaroot,'members',(SELECT jsonb_agg(to_jsonb(pt) ORDER BY pt.schemaname,pt.tablename) FROM pg_publication_tables pt WHERE pt.pubname=p.pubname)) ORDER BY p.pubname),'[]') FROM pg_publication p),
 'migrationHistory',(SELECT coalesce(jsonb_agg(jsonb_build_object('version',version,'name',name) ORDER BY version),'[]') FROM supabase_migrations.schema_migrations),
 'dependencies',(SELECT coalesce(jsonb_agg(jsonb_build_object('dependent',pg_identify_object(d.classid,d.objid,d.objsubid)::text,'referenced',pg_identify_object(d.refclassid,d.refobjid,d.refobjsubid)::text,'type',d.deptype) ORDER BY d.classid,d.objid,d.objsubid,d.refclassid,d.refobjid,d.refobjsubid),'[]') FROM pg_depend d WHERE (d.classid='pg_class'::regclass AND d.objid IN (SELECT oid FROM scoped_relations)) OR (d.classid='pg_proc'::regclass AND d.objid IN (SELECT oid FROM scoped_functions)) OR (d.classid='pg_rewrite'::regclass AND d.objid IN (SELECT oid FROM pg_rewrite WHERE ev_class IN (SELECT oid FROM scoped_relations))))
 ) AS snapshot;

