(async (page) => {
  const origin = /^(https?:\/\/[^/]+)/.exec(page.url())[1];
  if(origin !== 'http://127.0.0.1:3400') throw Error('Local acceptance origin required');
  const checks = [], api = [], errors = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('response', response => {
    const path = response.url().replace(/^https?:\/\/[^/]+/, '').split('?')[0];
    if(path.startsWith('/rest/v1/')) api.push({path,status:response.status()});
  });
  await page.goto(origin+'/dashboard', {waitUntil:'domcontentloaded'});
  await page.getByRole('link',{name:/Total de Pacientes/}).waitFor({state:'visible'});
  await page.getByRole('button',{name:'Nueva Cita',exact:true}).click();
  const editor = page.getByRole('dialog');
  await editor.getByRole('heading',{name:'Nueva cita',exact:true}).waitFor({state:'visible'});
  if(await editor.getByLabel('Notas clínicas').count()) throw Error('Reception clinical notes visible');
  checks.push('Reception booking opens without service catalogue or clinical notes');
  await editor.getByRole('combobox').filter({hasText:'Buscar paciente'}).click();
  await page.getByLabel('Buscar pacientes por nombre o teléfono').fill('Paciente inventado');
  await page.getByRole('option',{name:/Paciente inventado JWT A/}).click();
  await editor.getByLabel('Odontólogo',{exact:true}).selectOption({label:'Sintético doctor_A'});
  await editor.getByLabel('Fecha',{exact:true}).fill('2026-09-29');
  await editor.getByLabel('Hora',{exact:true}).fill('09:00');
  await editor.getByLabel('Duración (minutos)').fill('30');
  await editor.getByLabel('Motivo de la cita').fill('Control sintético navegador28');
  await editor.getByLabel('Estado',{exact:true}).selectOption('confirmed');
  const savedResponse = page.waitForResponse(response => response.url().endsWith('/rest/v1/rpc/save_clinic_appointment') && response.request().method()==='POST');
  await editor.getByRole('button',{name:'Guardar cita',exact:true}).click();
  const response = await savedResponse;
  if(!response.ok()) throw Error('Booking server rejected: '+response.status());
  const saved = await response.json();
  if(!saved.id || saved.start_time !== '2026-09-29T14:00:00+00:00' && Date.parse(saved.start_time)!==Date.parse('2026-09-29T14:00:00Z')) throw Error('Persisted schedule mismatch');
  await editor.waitFor({state:'hidden'});
  checks.push('Dashboard appointment persists at 09:00 Guayaquil (14:00 UTC)');
  await page.goto(origin+'/calendar?view=today',{waitUntil:'domcontentloaded'});
  await page.getByRole('status').filter({hasText:'citas en el periodo visible'}).waitFor({state:'visible'});
  await page.getByRole('button',{name:'Periodo siguiente',exact:true}).click();
  const row = page.getByRole('button').filter({hasText:'Control sintético navegador28'});
  await row.waitFor({state:'visible'});
  await row.click();
  const detail = page.getByRole('dialog');
  await detail.getByRole('button',{name:'Reprogramar',exact:true}).click();
  const reschedule = page.getByRole('dialog');
  await reschedule.getByLabel('Hora',{exact:true}).fill('10:00');
  if(await reschedule.getByLabel('Estado',{exact:true}).locator('option[value="scheduled"]').count()) throw Error('Forbidden confirmed-to-scheduled transition offered');
  await reschedule.getByRole('button',{name:'Guardar cita',exact:true}).click();
  await reschedule.waitFor({state:'hidden'});
  await page.reload({waitUntil:'domcontentloaded'});
  await page.getByRole('status').filter({hasText:'citas en el periodo visible'}).waitFor({state:'visible'});
  // Reload resets the viewed day to today, then next day verifies persisted edit.
  await page.getByRole('button',{name:'Periodo siguiente',exact:true}).click();
  await row.waitFor({state:'visible'});
  if(!(await row.innerText()).includes('10:00')) throw Error('Reprogramming did not survive reload');
  checks.push('Calendar finds persisted booking, reprograms and reloads at 10:00');
  await row.click();
  await page.getByRole('dialog').getByRole('button',{name:'En recepción',exact:true}).click();
  await page.getByRole('dialog').waitFor({state:'hidden'});
  await row.click();
  await page.getByRole('dialog').getByRole('button',{name:'Completada',exact:true}).click();
  await page.getByRole('dialog').waitFor({state:'hidden'});
  await row.waitFor({state:'visible'});
  if(!(await row.innerText()).includes('Completada')) throw Error('Completion not rendered');
  checks.push('Reception arrival and completion persist and refresh calendar');
  await page.setViewportSize({width:360,height:800});
  await page.waitForFunction(() => document.querySelector('#clinic-sidebar').getBoundingClientRect().right <= 0);
  const overflow = await page.evaluate(()=>document.documentElement.scrollWidth > innerWidth);
  if(overflow) throw Error('Calendar page horizontal overflow at 360px');
  await page.screenshot({path:'docs/production/evidence/2026-09-28-performance/calendar-reception-360.png',fullPage:true});
  checks.push('Reception calendar has no page horizontal overflow at 360px');
  if(errors.length) throw Error('Browser page errors: '+errors.join('; '));
  return {state:'VERIFIED_LOCAL_BOUNDED',role:'receptionist',appointmentId:saved.id,checks,api,errors};
})
