import * as z from "zod"

export const patientSchema = z.object({
  name: z.string().min(2, "El nombre es obligatorio (mín. 2 caracteres)"),
  lastName: z.string().min(2, "El apellido es obligatorio (mín. 2 caracteres)"),
  email: z.string().email("Correo electrónico inválido").optional().or(z.literal("")),
  phone: z.string().min(7, "El teléfono debe tener al menos 7 dígitos"),
  address: z.string().optional(),
  birthDate: z.string().min(1, "La fecha de nacimiento es obligatoria"),
  gender: z.string().optional(),
  occupation: z.string().optional(),
  guardianName: z.string().optional(),
  referralSource: z.string().optional(),
  referredBy: z.string().optional(),
  medicalRecordNumber: z.string().optional(),
  clinicalNotes: z.string().optional(),
  emergencyContact: z.string().optional(),
  emergencyPhone: z.string().optional(),
  allergies: z.string().optional(),
  medications: z.string().optional(),
  medicalConditions: z.string().optional(),
  insuranceProvider: z.string().optional(),
  policyNumber: z.string().optional(),
  bloodType: z.string().optional(),
  maritalStatus: z.string().optional(),
  city: z.string().optional(),
  state: z.string().optional(),
  hasDiabetes: z.boolean().default(false),
  hasHypertension: z.boolean().default(false),
  hasHeartDisease: z.boolean().default(false),
  isSmoker: z.boolean().default(false),
  isPregnant: z.boolean().default(false),
  preferredContactMethod: z.string().default("phone"),
  recallMonths: z.coerce.number().default(6),
  internalNotes: z.string().optional(),
  accountBalance: z.coerce.number().optional(),
})

export type PatientFormValues = z.infer<typeof patientSchema>
