const {test}=require('node:test')
const assert=require('node:assert/strict')
const {plan,stripSql}=require('../../scripts/restore-clinia-captured-schema.cjs')
test('restore planner assigns exact new local targets without reusing contract or primary databases',()=>{
  const stage=plan('stage','1'),linked=plan('linked','2')
  assert.equal(stage.database,'clinia_restore_stage_20261001_1')
  assert.equal(linked.database,'clinia_restore_linked_20261001_2')
  assert.equal(stage.source,'clinia_stage_clean')
  assert.equal(linked.source,'clinia_prod_upgrade')
  assert.notEqual(stage.database,stage.source)
  assert.notEqual(linked.database,linked.source)
  assert.equal(stage.tables,25);assert.equal(linked.functions,30)
  assert.equal(plan('linked','2',{managedTemplateStage:true}).source,'clinia_stage_clean')
  assert.throws(()=>plan('stage','1',{managedTemplateStage:true}))
  assert.throws(()=>plan('linked','2',{source:'postgres'}))
  for(const variant of ['prod','postgres','linked; DROP DATABASE postgres'])assert.throws(()=>plan(variant,'1'))
  for(const attempt of ['0','10','1;DROP DATABASE postgres','../1'])assert.throws(()=>plan('stage',attempt))
})
test('app stripping is bound to newly named targets; occupied primary/contract/source names are rejected',()=>{
  const sql=stripSql(plan('stage','3').database)
  assert.ok(sql.includes("current_database()<>'clinia_restore_stage_20261001_3'"))
  assert.ok(sql.includes('DROP SCHEMA IF EXISTS public CASCADE'))
  assert.ok(!sql.includes('DROP DATABASE'))
  for(const database of ['postgres','clinia_stage_clean','clinia_contract_stage_20260928_3','clinia_restore_stage_20261001_1;DROP DATABASE postgres'])assert.throws(()=>stripSql(database))
})
