'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { generate, verify, parseAcl, hash } = require('../../scripts/generate-scoped-supabase-baseline.cjs');
const evidence = path.resolve(__dirname, '../../docs/production/evidence/2026-09-27');
const read = name => JSON.parse(fs.readFileSync(path.join(evidence, name), 'utf8'));
const stage = read('catalog-stage-scoped.metadata.json');
const prod = read('catalog-prod-scoped.metadata.json');
const stageDeps = read('catalog-stage-dependencies.metadata.json');
const prodDeps = read('catalog-prod-dependencies.metadata.json');
const options = { target: 'local-synthetic' };
const fixture = (s = stage, d = stageDeps, extra = {}) => generate(s, d, { ...options, ...extra });
const observed = { mode: 'observed-fixture', acknowledgeObservedFixture: true };

test('Generation requires local target and explicit acknowledgement for historical ACL replay', () => {
  assert.throws(() => generate(stage, stageDeps), /Explicit target/);
  assert.throws(() => fixture(stage, stageDeps, { mode: 'observed-fixture' }), /explicit acknowledgement/);
  assert.equal(fixture(stage, stageDeps).manifest.mode, 'deny-client');
});
test('Both real captures produce deterministic complete scoped fixtures with all dependencies accounted', () => {
  for (const [s, d] of [[stage, stageDeps], [prod, prodDeps]]) {
    const a = fixture(s, d, observed), b = fixture(s, d, observed);
    assert.equal(a.sql, b.sql);
    assert.equal(a.manifest.sqlSha256, hash(a.sql));
    for (const category of Object.keys(a.manifest.coverage)) {
      const expectedCount = category === 'dependencies' ? d.dependencies.length : s[category].length;
      assert.equal(a.manifest.coverage[category].length, expectedCount, category);
      assert.ok(a.manifest.coverage[category].every(x => x.disposition && x.sourceHash));
    }
    assert.equal(a.manifest.deployable, false);
  }
});
test('Default privileges are neutralized before application types/tables/functions; source remote defaults never replayed', () => {
  const { sql, manifest } = fixture(prod, prodDeps, observed);
  assert.ok(sql.indexOf('ALTER DEFAULT PRIVILEGES') < sql.indexOf('CREATE TYPE'));
  assert.ok(sql.indexOf('ALTER DEFAULT PRIVILEGES') < sql.indexOf('CREATE TABLE'));
  assert.ok(sql.includes('ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" REVOKE ALL ON FUNCTIONS FROM PUBLIC'));
  assert.ok(sql.includes('ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" REVOKE ALL ON TYPES FROM PUBLIC'));
  assert.ok(!sql.includes('ALTER DEFAULT PRIVILEGES') || !/ALTER DEFAULT PRIVILEGES[^;]+GRANT/.test(sql));
  assert.equal(manifest.coverage.defaultPrivileges.filter(x => x.reason.includes('not replayed')).length, prod.defaultPrivileges.length);
});
test('Exact typmods, int64 sequence bounds, identity and serial ownership preserve captured differences', () => {
  const p = fixture(prod, prodDeps, observed), s = fixture();
  assert.match(p.sql, /"size" character varying\(50\)/);
  assert.match(p.sql, /"price" numeric\(10,2\)/);
  assert.match(p.sql, /"amount" numeric\(10,2\)/);
  assert.match(p.sql, /MAXVALUE 9223372036854775807/);
  assert.match(p.sql, /GENERATED BY DEFAULT AS IDENTITY \(SEQUENCE NAME "logs"\."access_audit_id_seq"/);
  assert.match(p.sql, /ALTER SEQUENCE "public"\."profile_audit_log_id_seq" OWNED BY "public"\."profile_audit_log"\."id"/);
  assert.ok(!s.sql.includes('profile_audit_log_id_seq" OWNED BY'));
  assert.ok(!p.sql.includes('ALTER SEQUENCE "logs"."access_audit_id_seq" OWNER'));
  assert.ok(p.sql.indexOf('CREATE SEQUENCE "public"."profile_audit_log_id_seq"') < p.sql.indexOf('CREATE TABLE "public"."profile_audit_log"'));
});
test('Tables precede foreign keys; unique parent constraints precede composite M7 references', () => {
  const { sql } = fixture();
  assert.ok(sql.indexOf('CREATE TABLE "public"."clinics"') < sql.indexOf('ADD CONSTRAINT "profiles_clinic_id_fkey"'));
  assert.ok(sql.indexOf('ADD CONSTRAINT "patients_id_clinic_id_key"') < sql.indexOf('ADD CONSTRAINT "appointments_patient_clinic_fkey"'));
  assert.ok(sql.includes('ON DELETE SET NULL (patient_id)'));
  assert.equal((sql.match(/CREATE TRIGGER trg_audit_data_rights_status/g) || []).length, 1);
});
test('Original function definitions are copied without fixing source defects or remote history', () => {
  const p = fixture(prod, prodDeps, observed), s = fixture();
  for (const f of prod.functions) assert.ok(p.sql.includes(f.definition.trimEnd() + ';'), f.name);
  const badAudit = prod.functions.find(f => f.schema === 'logs' && f.name === 'log_patient_view');
  assert.ok(badAudit.definition.includes('user_id'));
  assert.ok(!prod.columns.some(c => c.schema === 'logs' && c.table === 'access_audit' && c.name === 'user_id'));
  assert.ok(!p.sql.includes('INSERT INTO supabase_migrations'));
  assert.ok(!s.sql.includes('DROP TABLE'));
  assert.ok(p.sql.includes('CREATE TRIGGER on_auth_user_created'));
  assert.ok(s.sql.includes('CREATE VIEW "public"."receptionist_patient_view"'));
});
test('Deny-client strips effective function/table/schema/column grants and omits historical Storage policies', () => {
  const { manifest, sql } = fixture(prod, prodDeps);
  const expected = manifest.expectedScopedState;
  assert.equal(expected.policies.filter(p => p.schemaname === 'storage').length, 0);
  assert.ok(expected.buckets.every(b => b.public === false));
  for (const f of expected.functions) assert.equal(f.acl, '{' + f.owner + '=X/' + f.owner + '}');
  assert.ok(!/^GRANT .+ TO (PUBLIC|"anon"|"authenticated"|"service_role");$/m.test(sql));
  assert.equal(manifest.coverage.policies.filter(x => x.disposition === 'explicitly-omitted').length, prod.policies.filter(p => p.schemaname === 'storage').length);
});
test('Null ACL semantics and grant options are modeled; malformed or unreviewed grants fail closed', () => {
  assert.ok(parseAcl(null, 'FUNCTION', 'postgres').some(a => a.grantee === 'PUBLIC'));
  assert.ok(!parseAcl(null, 'TABLE', 'postgres').some(a => a.grantee === 'PUBLIC'));
  assert.deepEqual(parseAcl('{authenticated=r*/postgres}', 'TABLE', 'postgres')[0].grantOptions, ['r']);
  for (const acl of ['{outsider=r/postgres}', '{"authenticated"=r/postgres}', '{authenticated=z/postgres}', '{authenticated=r/supabase_admin}']) assert.throws(() => parseAcl(acl, 'TABLE', 'postgres'));
});
test('Unsupported/missing structural and dependency categories fail closed before output', () => {
  for (const mutate of [
    s => { delete s.sequences; },
    s => { s.relations[0].kind = 'p'; },
    s => { s.types[0].kind = 'd'; },
    s => { s.columns[0].generated = 's'; },
    s => { s.indexes[0].valid = false; },
    s => { s.functions[0].acl = '{unknown=X/postgres}'; },
    s => { s.columns[0].typeName = 'unsupported'; },
    s => { s.relations.push({ ...s.relations[0] }); },
  ]) { const s = structuredClone(stage); mutate(s); assert.throws(() => fixture(s)); }
  const d = structuredClone(stageDeps); d.dependencies.push({ dependent: '(table,public,patients,public.patients)', referenced: '(table,external,secret,external.secret)', type: 'n' });
  assert.throws(() => fixture(stage, d), /external dependency/);
  const bad = structuredClone(stageDeps); bad.projectRef = 'wrong';
  assert.throws(() => fixture(stage, bad), /Matching supplemental/);
});
test('Unexpected filesystem/network/credential operations in copied metadata fail closed', () => {
  for (const payload of ["PERFORM net.http_post('x');", "PERFORM pg_read_file('x');", "PERFORM dblink('x','y');", "PERFORM 'https://example.com';", "PERFORM 'sb_secret_abcdefghijklmnop';"]) {
    const s = structuredClone(stage); s.functions[0].definition += '\n' + payload; assert.throws(() => fixture(s), /rejected/);
  }
});
test('Scoped verifier catches missing constraints, enum order, ACL escalation and shape changes', () => {
  const { manifest } = fixture(prod, prodDeps, observed);
  const exact = structuredClone(manifest.expectedScopedState);
  assert.equal(verify(manifest, exact).matches, true);
  for (const mutate of [
    s => { s.constraints.pop(); },
    s => { s.types[0].enumLabels.reverse(); },
    s => { s.functions[0].acl = '{postgres=X/postgres,anon=X/postgres}'; },
    s => { s.columns.find(c => c.table === 'services' && c.name === 'price').type = 'numeric'; },
    s => { s.sequences[1].ownedBy = null; },
    s => { s.triggers.pop(); },
    s => { s.relations.find(r => r.kind === 'v').options = null; },
    s => { s.defaultPrivileges[0].acl = '{postgres=X/postgres,anon=X/postgres}'; },
    s => { s.defaultPrivileges = []; },
  ]) { const changed = structuredClone(exact); mutate(changed); assert.equal(verify(manifest, changed).matches, false); }
});
test('Observed fixture restores column-level profile permissions and SQL MAINTAIN rights; defaults remain deliberately different', () => {
  const { sql, manifest } = fixture(prod, prodDeps, observed);
  assert.match(sql, /GRANT UPDATE \("full_name"\) ON "public"\."profiles" TO "authenticated"/);
  assert.match(sql, /MAINTAIN/);
  assert.ok(manifest.explicitDifferences.some(x => x.category === 'defaultPrivileges'));
  assert.ok(manifest.verificationBoundary.some(x => x.includes('historical defects')));
});
test('Dropped physical slots compact explicitly; logical reordering and invalid positions still fail', () => {
  const {manifest}=fixture();
  assert.equal(manifest.formatVersion,2);
  assert.ok(manifest.explicitDifferences.some(x=>x.identity==='public.data_rights_requests.resolution_notes' && x.reason.includes('16 compacts to 15')));
  const actual=structuredClone(manifest.expectedScopedState);
  actual.columns.find(c=>c.table==='data_rights_requests' && c.name==='resolution_notes').position=15;
  const comparison=verify(manifest,actual);
  assert.equal(comparison.matches,true);
  assert.deepEqual(comparison.physicalColumnPositionDifferences,[{identity:'public.data_rights_requests.resolution_notes',expectedPhysical:16,actualPhysical:15}]);
  const table=actual.columns.filter(c=>c.table==='patients');
  [table[0].position,table[1].position]=[table[1].position,table[0].position];
  assert.equal(verify(manifest,actual).matches,false);
  table[0].position=table[1].position;
  assert.throws(()=>verify(manifest,actual),/Duplicate column/);
  table[0].position=-1;
  assert.throws(()=>verify(manifest,actual),/Invalid physical/);
});
